spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create-drop # Automatically create and drop tables for each test run
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
