name: Gradle CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

steps:
  # Step 1: Check out the code
  - name: Checkout code
    uses: actions/checkout@v3

  # Step 2: Set up JDK 20
  - name: Set up JDK 20
    uses: actions/setup-java@v3
    with:
      java-version: 20
      distribution: 'temurin'

  # Step 3: Fix gradlew permissions for Linux runners
  - name: Fix permissions for gradlew
    run: chmod +x ./gradlew

  # Step 4: Build and Test with Gradle
  - name: Build with Gradle
    run: ./gradlew build


